# Generated by Django 5.0.4 on 2024-04-27 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugreport',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
