# Generated by Django 5.0.4 on 2024-04-27 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0002_rename_update_at_bugreport_updated_at'),
        ('tasks', '0002_task_delete_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.task'),
        ),
    ]
